export class Letter {
    id: number;
    consonant: string;
    katakana: string;
    vowel: string;
    romaji: string;
    hiragana: string;
    isactive: boolean;
}

export const letters = [
    {
        id: 46,
        consonant: '',
        katakana: 'ン',
        vowel: '',
        romaji: 'n/m',
        hiragana: 'ん',
        isactive: false,
    },
    {
        id: 44,
        consonant: 'w',
        katakana: 'ワ',
        vowel: 'a',
        romaji: 'wa',
        hiragana: 'わ',
        isactive: false,
    },
    {
        id: 45,
        consonant: 'w',
        katakana: 'ヲ',
        vowel: 'o',
        romaji: 'wo',
        hiragana: 'を',
        isactive: false,
    },
    {
        id: 39,
        consonant: 'r',
        katakana: 'ラ',
        vowel: 'a',
        romaji: 'ra',
        hiragana: 'ら',
        isactive: false,
    },
    {
        id: 40,
        consonant: 'r',
        katakana: 'リ',
        vowel: 'i',
        romaji: 'ri',
        hiragana: 'り',
        isactive: false,
    },
    {
        id: 41,
        consonant: 'r',
        katakana: 'ル',
        vowel: 'u',
        romaji: 'ru',
        hiragana: 'る',
        isactive: false,
    },
    {
        id: 42,
        consonant: 'r',
        katakana: 'レ',
        vowel: 'e',
        romaji: 're',
        hiragana: 'れ',
        isactive: false,
    },
    {
        id: 43,
        consonant: 'r',
        katakana: 'ロ',
        vowel: 'o',
        romaji: 'ro',
        hiragana: 'ろ',
        isactive: false,
    },
    {
        id: 36,
        consonant: 'y',
        katakana: 'ヤ',
        vowel: 'a',
        romaji: 'ya',
        hiragana: 'や',
        isactive: false,
    },
    {
        id: 37,
        consonant: 'y',
        katakana: 'ユ',
        vowel: 'u',
        romaji: 'yu',
        hiragana: 'ゆ',
        isactive: false,
    },
    {
        id: 38,
        consonant: 'y',
        katakana: 'ヨ',
        vowel: 'o',
        romaji: 'yo',
        hiragana: 'よ',
        isactive: false,
    },
    {
        id: 31,
        consonant: 'm',
        katakana: 'マ',
        vowel: 'a',
        romaji: 'ma',
        hiragana: 'ま',
        isactive: false,
    },
    {
        id: 32,
        consonant: 'm',
        katakana: 'ミ',
        vowel: 'i',
        romaji: 'mi',
        hiragana: 'み',
        isactive: false,
    },
    {
        id: 33,
        consonant: 'm',
        katakana: 'ム',
        vowel: 'u',
        romaji: 'mu',
        hiragana: 'む',
        isactive: false,
    },
    {
        id: 34,
        consonant: 'm',
        katakana: 'メ',
        vowel: 'e',
        romaji: 'me',
        hiragana: 'め',
        isactive: false,
    },
    {
        id: 35,
        consonant: 'm',
        katakana: 'モ',
        vowel: 'o',
        romaji: 'mo',
        hiragana: 'も',
        isactive: false,
    },
    {
        id: 26,
        consonant: 'h',
        katakana: 'ハ',
        vowel: 'a',
        romaji: 'ha',
        hiragana: 'は',
        isactive: false,
    },
    {
        id: 27,
        consonant: 'h',
        katakana: 'ヒ',
        vowel: 'i',
        romaji: 'hi',
        hiragana: 'ひ',
        isactive: false,
    },
    {
        id: 28,
        consonant: 'h',
        katakana: 'フ',
        vowel: 'u',
        romaji: 'fu',
        hiragana: 'ふ',
        isactive: false,
    },
    {
        id: 29,
        consonant: 'h',
        katakana: 'ヘ',
        vowel: 'e',
        romaji: 'he',
        hiragana: 'へ',
        isactive: false,
    },
    {
        id: 30,
        consonant: 'h',
        katakana: 'ホ',
        vowel: 'o',
        romaji: 'ho',
        hiragana: 'ほ',
        isactive: false,
    },
    {
        id: 21,
        consonant: 'n',
        katakana: 'ナ',
        vowel: 'a',
        romaji: 'na',
        hiragana: 'な',
        isactive: false,
    },
    {
        id: 22,
        consonant: 'n',
        katakana: 'ニ',
        vowel: 'i',
        romaji: 'ni',
        hiragana: 'に',
        isactive: false,
    },
    {
        id: 23,
        consonant: 'n',
        katakana: 'ヌ',
        vowel: 'u',
        romaji: 'nu',
        hiragana: 'ぬ',
        isactive: false,
    },
    {
        id: 24,
        consonant: 'n',
        katakana: 'ネ',
        vowel: 'e',
        romaji: 'ne',
        hiragana: 'ね',
        isactive: false,
    },
    {
        id: 25,
        consonant: 'n',
        katakana: 'ノ',
        vowel: 'o',
        romaji: 'no',
        hiragana: 'の',
        isactive: false,
    },
    {
        id: 16,
        consonant: 't',
        katakana: 'タ',
        vowel: 'a',
        romaji: 'ta',
        hiragana: 'た',
        isactive: false,
    },
    {
        id: 17,
        consonant: 't',
        katakana: 'チ',
        vowel: 'i',
        romaji: 'chi',
        hiragana: 'ち',
        isactive: false,
    },
    {
        id: 18,
        consonant: 't',
        katakana: 'ツ',
        vowel: 'u',
        romaji: 'tsu',
        hiragana: 'つ',
        isactive: false,
    },
    {
        id: 19,
        consonant: 't',
        katakana: 'テ',
        vowel: 'e',
        romaji: 'te',
        hiragana: 'て',
        isactive: false,
    },
    {
        id: 20,
        consonant: 't',
        katakana: 'ト',
        vowel: 'o',
        romaji: 'to',
        hiragana: 'と',
        isactive: false,
    },
    {
        id: 11,
        consonant: 's',
        katakana: 'サ',
        vowel: 'a',
        romaji: 'sa',
        hiragana: 'さ',
        isactive: false,
    },
    {
        id: 12,
        consonant: 's',
        katakana: 'シ',
        vowel: 'i',
        romaji: 'shi',
        hiragana: 'し',
        isactive: false,
    },
    {
        id: 13,
        consonant: 's',
        katakana: 'ス',
        vowel: 'u',
        romaji: 'su',
        hiragana: 'す',
        isactive: false,
    },
    {
        id: 14,
        consonant: 's',
        katakana: 'セ',
        vowel: 'e',
        romaji: 'se',
        hiragana: 'せ',
        isactive: false,
    },
    {
        id: 15,
        consonant: 's',
        katakana: 'ソ',
        vowel: 'o',
        romaji: 'so',
        hiragana: 'そ',
        isactive: false,
    },
    {
        id: 6,
        consonant: 'k',
        katakana: 'カ',
        vowel: 'a',
        romaji: 'ka',
        hiragana: 'か',
        isactive: false,
    },
    {
        id: 7,
        consonant: 'k',
        katakana: 'キ',
        vowel: 'i',
        romaji: 'ki',
        hiragana: 'き',
        isactive: false,
    },
    {
        id: 8,
        consonant: 'k',
        katakana: 'ク',
        vowel: 'u',
        romaji: 'ku',
        hiragana: 'く',
        isactive: false,
    },
    {
        id: 9,
        consonant: 'k',
        katakana: 'ケ',
        vowel: 'e',
        romaji: 'ke',
        hiragana: 'け',
        isactive: false,
    },
    {
        id: 10,
        consonant: 'k',
        katakana: 'コ',
        vowel: 'o',
        romaji: 'ko',
        hiragana: 'こ',
        isactive: false,
    },
    {
        id: 1,
        consonant: 'vowel',
        katakana: 'ア',
        vowel: 'a',
        romaji: 'a',
        hiragana: 'あ',
        isactive: false,
    },
    {
        id: 2,
        consonant: 'vowel',
        katakana: 'イ',
        vowel: 'i',
        romaji: 'i',
        hiragana: 'い',
        isactive: false,
    },
    {
        id: 3,
        consonant: 'vowel',
        katakana: 'ウ',
        vowel: 'u',
        romaji: 'u',
        hiragana: 'う',
        isactive: false,
    },
    {
        id: 4,
        consonant: 'vowel',
        katakana: 'エ',
        vowel: 'e',
        romaji: 'e',
        hiragana: 'え',
        isactive: false,
    },
    {
        id: 5,
        consonant: 'vowel',
        katakana: 'オ',
        vowel: 'o',
        romaji: 'o',
        hiragana: 'お',
        isactive: false,
    }
]